# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RNWheresMy' do
  # Pods for RNWheresMy
  target 'RNWheresMyTests' do
    pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  end
end
